import type { NextPage } from 'next'
import Head from 'next/head'
import { About } from '../components/About'

import { Header } from '../components/Header'
import { Projects } from '../components/Projects'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <About/>
      <Projects/>
    </div>
  )
}

export default Home
